import product1 from "./assets/img/products/product-1.png";
import product2 from "./assets/img/products/product-2.png";
import product3 from "./assets/img/products/product-3.png";
import product4 from "./assets/img/products/product-4.png";
import product5 from "./assets/img/products/product-5.png";
import product6 from "./assets/img/products/product-6.png";
import product7 from "./assets/img/products/product-7.png";
import product8 from "./assets/img/products/product-8.png";
import product9 from "./assets/img/products/product-9.png";

export const products = [
  {
    id: 1,
    title: "Nike Air Max 270 React",
    rating: 3.6,
    price: 245,
    img: product1,
    imgs: [product6, product4, product5],
    discount: 15,
    brand: "Nike",
    category: "Shoes",
    freeShipping: false,
    colors: ["red", "green", "blue"],
    sizes: ["SM", "MD", "LG"],
    available: 25,
    label: "HOT",
    reviews: [],
    reviewsCount: 3,
    description: "Greet Product",
    active: true,
  },
  {
    id: 2,
    title: "Nike Air Max 270 React",
    rating: 4.5,
    price: 324.69,
    img: product2,
    discount: 30,
    brand: "Nike",
    category: "Shoes",
    freeShipping: false,
    colors: ["red", "green", "blue"],
    sizes: ["SM", "MD", "LG"],
    available: 25,
    reviews: [],
    description: "Greet Product",
    active: true,
  },
  {
    id: 3,
    title: "Nike Air Max 270 React",
    rating: 4.5,
    price: 324.69,
    img: product3,
    discount: 30,
    brand: "Nike",
    category: "Shoes",
    freeShipping: false,
    colors: ["red", "green", "blue"],
    sizes: ["SM", "MD", "LG"],
    available: 25,
    reviews: [],
    description: "Greet Product",
    active: true,
  },
  {
    id: 4,
    title: "Nike Air Max 270 React",
    rating: 4.5,
    price: 324.69,
    img: product4,
    discount: 30,
    brand: "Nike",
    category: "Shoes",
    freeShipping: false,
    colors: ["red", "green", "blue"],
    sizes: ["SM", "MD", "LG"],
    available: 25,
    reviews: [],
    description: "Greet Product",
    active: true,
  },
  {
    id: 5,
    title: "Nike Air Max 270 React",
    rating: 4.5,
    price: 324.69,
    img: product5,
    discount: 30,
    brand: "Nike",
    category: "Shoes",
    freeShipping: false,
    colors: ["red", "green", "blue"],
    sizes: ["SM", "MD", "LG"],
    available: 25,
    reviews: [],
    description: "Greet Product",
    active: true,
  },
  {
    id: 6,
    title: "Nike Air Max 270 React",
    rating: 4.5,
    price: 324.69,
    img: product6,
    discount: 30,
    brand: "Nike",
    category: "Shoes",
    freeShipping: false,
    colors: ["red", "green", "blue"],
    sizes: ["SM", "MD", "LG"],
    available: 25,
    reviews: [],
    description: "Greet Product",
    active: true,
  },
  {
    id: 7,
    title: "Nike Air Max 270 React",
    rating: 4.5,
    price: 324.69,
    img: product7,
    discount: 30,
    brand: "Nike",
    category: "Shoes",
    freeShipping: false,
    colors: ["red", "green", "blue"],
    sizes: ["SM", "MD", "LG"],
    available: 25,
    reviews: [],
    description: "Greet Product",
    active: true,
  },
  {
    id: 8,
    title: "Nike Air Max 270 React",
    rating: 4.5,
    price: 324.69,
    img: product8,
    discount: 30,
    brand: "Nike",
    category: "Shoes",
    freeShipping: false,
    colors: ["red", "green", "blue"],
    sizes: ["SM", "MD", "LG"],
    available: 25,
    reviews: [],
    description: "Greet Product",
    active: true,
  },
  {
    id: 9,
    title: "Nike Air Max 270 React",
    rating: 4.5,
    price: 324.69,
    img: product9,
    discount: 30,
    brand: "Nike",
    category: "Shoes",
    freeShipping: false,
    colors: ["red", "green", "blue"],
    sizes: ["SM", "MD", "LG"],
    available: 25,
    reviews: [],
    description: "Greet Product",
    active: true,
  },
];
